#ifndef DASHBOARD_PAGE_FIRMWARE_H
#define DASHBOARD_PAGE_FIRMWARE_H

#include <App/Global.h>
#include <App/Dashboard/Partials/Modals/Firmware.h>

namespace App {
  namespace DashboardPageFirmware {
    const char Main[] PROGMEM = R"PAGE(
<main class=dashboard-main><div class=dashboard-section><div class="dashboard-content dashboard-content-narrow"><div class=breadcrumbs><a href=/index.html class=breadcrumbs-item><span data-t=home></span></a><a href=/settings.html class=breadcrumbs-item><span data-t=settings></span></a><span class=breadcrumbs-item><span data-t=firmware></span></span></div></div></div><div class=dashboard-section><div class="dashboard-content dashboard-content-narrow"><div class="flex flex-column flex-gap-medium"><div class="group flex-item-grow mb-3"><a href=/settings.html class="group-item button button-icon"><i class="icon icon-grid"></i></a><div class="flex-item-grow flex dropdown"><div class="group-item flex-item-grow select" data-t=firmware></div><div class=dropdown-items><a href=/settings/display.html class=dropdown-link data-t=display_eink></a><a href=/settings/network.html class=dropdown-link data-t=network_ap_sta></a><a href=/settings/mdns.html class=dropdown-link data-t=mdns_local_name></a><a href=/settings/ntp.html class=dropdown-link data-t=ntp_sync></a><a href=/settings/datetime.html class=dropdown-link data-t=rtc_datetime></a><a href=/settings/wakeup.html class=dropdown-link data-t=rtc_wakeup></a><a href=/settings/language.html class=dropdown-link data-t=language></a><a href=/settings/user.html class=dropdown-link data-t=user></a><a href=/settings/storage.html class=dropdown-link data-t=storage></a><a href=/settings/firmware.html class="dropdown-link active" data-t=firmware></a></div></div></div><div class="mb-2 mt-0 card-alert" data-dismiss-session=firmware-info-hint><div class=card-alert-icon><i class="icon icon-lightbulb"></i></div><small class=card-alert-text data-t=firmware_page_info></small><button class=card-alert-close type=button data-card-close></button></div><div class="card-info mt-0 mb-2" data-dismiss-session=firmware-bin-hint><div class=card-info-icon><i class="icon icon-exclamation-triangle"></i></div><div class=card-info-text data-t=firmware_bin_only></div><button class=card-info-close type=button aria-label data-t-aria-label=close data-card-close></button></div><div class="upload mb-0"><form class="upload-dropzone clickable mb-2" action=# data-firmware-upload data-invalid-file-message data-t-data-invalid-file-message=firmware_bin_only data-success-file-message data-t-data-success-file-message=firmware_upload_success data-upload-progress-template data-t-data-upload-progress-template=firmware_upload_progress data-upload-default-file-name=firmware.bin><input id=firmware-file-input type=file name=firmware accept=.bin,application/octet-stream hidden data-firmware-input><small for=firmware-file-input data-firmware-label data-t=firmware_drop_hint></small></form></div><p class=m-0><span data-t=firmware_version></span>&nbsp;<span class=badge data-firmware-version>__PROJECT_VERSION__</span></p></div></div></div></main>
)PAGE";
    const char *Extra = DashboardFirmwareModals::Extra;
  }
}

#endif