#ifndef DASHBOARD_PAGE_L_LANG_H
#define DASHBOARD_PAGE_L_LANG_H

#include <App/Global.h>
#include <App/Dashboard/Partials/Modals/Common.h>

namespace App {
  namespace DashboardPageLanguage {
    const char Main[] PROGMEM = R"PAGE(
<main class=dashboard-main><div class=dashboard-section><div class="dashboard-content dashboard-content-narrow"><div class=breadcrumbs><a href=/index.html class=breadcrumbs-item><span data-t=home></span></a><a href=/settings.html class=breadcrumbs-item><span data-t=settings></span></a><span class=breadcrumbs-item><span data-t=language></span></span></div></div></div><div class=dashboard-section><div class="dashboard-content dashboard-content-narrow"><div class="flex flex-column flex-gap-medium"><div class="group flex-item-grow mb-3"><a href=/settings.html class="group-item button button-icon"><i class="icon icon-grid"></i></a><div class="flex-item-grow flex dropdown"><div class="group-item flex-item-grow select" data-t=language></div><div class=dropdown-items><a href=/settings/display.html class=dropdown-link data-t=display_eink></a><a href=/settings/network.html class=dropdown-link data-t=network_ap_sta></a><a href=/settings/mdns.html class=dropdown-link data-t=mdns_local_name></a><a href=/settings/ntp.html class=dropdown-link data-t=ntp_sync></a><a href=/settings/datetime.html class=dropdown-link data-t=rtc_datetime></a><a href=/settings/wakeup.html class=dropdown-link data-t=rtc_wakeup></a><a href=/settings/language.html class="dropdown-link active" data-t=language></a><a href=/settings/user.html class=dropdown-link data-t=user></a><a href=/settings/storage.html class=dropdown-link data-t=storage></a><a href=/settings/firmware.html class=dropdown-link data-t=firmware></a></div></div></div><div class="mb-2 mt-0 card-alert" data-dismiss-session=language-info-hint><div class=card-alert-icon><i class="icon icon-lightbulb"></i></div><small class=card-alert-text data-t=language_page_info></small><button class=card-alert-close type=button data-card-close></button></div><form data-language-form data-language-save-success-message data-language-save-error-message data-t-data-language-save-success-message=language_save_success data-t-data-language-save-error-message=language_save_error ><template data-form-alert-template></template><div class=card><div class=card-body><div class="field mt-1"><div><label class=field-label for=field-language><span data-t=interface_language></span></label></div><div class=select><span data-t=en></span><select id=field-language name=language>__LANG_OPTIONS__</select></div></div><div class="field mt-3"><div><label class="field-label mb-0"><span data-t=enable_languages_description></span></label></div><div class="field-grid-2" style=row-gap:.75rem data-language-enabled-languages></div></div></div><div class="card-footer card-footer-equal-2"><div></div><button type=submit class="button button-primary"><i class="icon icon-save"></i><span data-t=save></span></button></div></div></form></div></div></div></main>
)PAGE";
    const char *Extra = DashboardCommonModals::kSidebarCommonExtraHtml;
  }
}

#endif