#ifndef DASHBOARD_H
#define DASHBOARD_H

#include <App/Global.h>

namespace App {

  struct SSession {
    char Token[65] = {};
    uint32_t LastSeenMs = 0;
    bool Active = false;
  };

  struct SImageUploadContext {
    File Handle;
    bool Ok = true;
    bool IsThumb = false;
    bool IsLinkedUpload = false;
    size_t Written = 0;
    size_t Expected = 0;
    char StorageKey[24] = {};
    char FileName[97] = {};
    char Path[192] = {};
    char Message[64] = "queue_save_error";
  };

  class Dashboard_ {
    DEFINE_TAG("DSH");
    friend class AutoGuard<Dashboard_>;
    public:
      using Guard = AutoGuard<Dashboard_>;
      static Dashboard_ &Instance();
      void Init(FDefaultCallback tOnReboot = nullptr, FDefaultCallback tOnReset = nullptr);
      void ReloadConfig();
      void Start();
      void Stop();
      void HandleEvents();
    private:
      Dashboard_();
      Dashboard_(const Dashboard_&) = delete;
      Dashboard_ &operator=(const Dashboard_&) = delete;
      ~Dashboard_();
      SAppConfig mCfg {};
      static void Lock();
      static void Unlock();
      struct SWebSocketClientContext {
        char Token[65] = {};
      };
      static constexpr uint8_t kMaxSessions = 3;
      static constexpr uint32_t kSessionTtlSec = 30 * 60;
      static constexpr uint32_t kBroadcastIntervalMs = 60 * 1000;
      static constexpr uint32_t kStatusCacheRefreshIntervalMs = 1000;
      static constexpr uint32_t kStatsCacheRefreshIntervalMs = 1000;
      static constexpr uint32_t kOtaProgressBroadcastIntervalMs = 250;
      static constexpr uint32_t kOtaFinalizeTimeoutMs = 20000;
      static constexpr uint32_t kStorageStatsCacheTtlMs = 5000;
      static constexpr uint32_t kIndexDataCacheRefreshIntervalMs = 3000;
      static constexpr uint32_t kRestartActionDelayMs = 3 * 1000;
      static constexpr size_t kSmallJsonSize = 512;
      static constexpr size_t kConfigJsonSize = 2 * 1024;
      static constexpr size_t kImagesJsonSize = 8 * 1024;
      static constexpr size_t kStatsJsonSize = 2 * 1024;
      static constexpr size_t kMaxUploadFileNameLength = 96;
      static constexpr const char *kSessionCookieName = "token";
      mutable SemaphoreHandle_t mMutex = nullptr;
      AsyncWebServer mServer {80};
      AsyncWebSocket *mWebSocket = nullptr;
      FDefaultCallback mOnReboot = nullptr;
      FDefaultCallback mOnReset = nullptr;
      uint32_t mLastBroadcast = 0;
      SSession mSessions[kMaxSessions] = {};
      char mCachedUser[64] = {};
      char mCachedPassHash[65] = {};
      bool mRestartPending = false;
      bool mResetPending = false;
      uint32_t mRestartPendingSince = 0;
      uint32_t mResetPendingSince = 0;
      uint32_t mLastStatusCacheRefreshMs = 0;
      uint32_t mLastStatsCacheRefreshMs = 0;
      char mCachedStatusJson[kSmallJsonSize] = "{}";
      char mCachedStatsJson[kStatsJsonSize] = "{}";
      bool mStatsCacheDirty = true;
      String mCachedPageStatsDataJson = "";
      uint32_t mLastStorageStatsCacheMs = 0;
      uint64_t mCachedSdTotalBytes = 0;
      uint64_t mCachedSdUsedBytes = 0;
      uint64_t mCachedLfsTotalBytes = 0;
      uint64_t mCachedLfsUsedBytes = 0;
      uint32_t mLastIndexDataCacheRefreshMs = 0;
      bool mIndexDataCacheDirty = true;
      uint32_t mCachedIndexGalleryCount = 0;
      String mCachedIndexStoragesJson = "";
      uint32_t mLastOtaProgressBroadcastMs = 0;
      uint8_t mLastOtaProgressPercent = 0xFF;
      bool mRoutesRegistered = false;
      bool mServerStarted = false;
      static String EscapeJsonText(const String &tValue);
      static bool ParseBoolValue(const String &tValue);
      static bool TryGetRequestValue(AsyncWebServerRequest *tRequest, const char *tKey, String &tValue);
      static String EncodeUrlComponent(const String &tValue);
      static bool IsDarkLogoAssetPath(const char *tPath);
      static String CopyProgmemText(const char *tData);
      static String BuildDarkLogoSvg(const char *tLightSvgData);
      static String ResolveSafeRedirectTarget(AsyncWebServerRequest *tRequest, const String &tFallback = String("/index.html"));
      static String BuildLoginRedirectUrl(AsyncWebServerRequest *tRequest, const String &tRequestedPath = String());
      static int ResolveErrorStatusCode(int tRequestedCode);
      static int ResolveErrorStatusCodeFromRequest(AsyncWebServerRequest *tRequest);
      static const char *ResolveErrorTitleKey(int tCode);
      static const char *ResolveErrorMessageKey(int tCode);
      static String BuildErrorPageMainHtml(int tCode, bool tAuthorized);
      static bool TryExtractBearerToken(AsyncWebServerRequest *tRequest, char *tToken, size_t tTokenSize);
      static SWebSocketClientContext *GetWebSocketClientContext(AsyncWebSocketClient *tClient, bool tCreate = false);
      static void ReleaseWebSocketClientContext(AsyncWebSocketClient *tClient);
      static std::vector<String> GetRequestValues(AsyncWebServerRequest *tRequest, const char *tKey);
      static String ResolvePageKeyFromRequest(AsyncWebServerRequest *tRequest);
      static const char *ResolveContractPageName(const String &tPageKey);
      static String NormalizeTimeZoneLabel(const String &tTimeZoneLabel);
      static String FormatUtcOffsetLabel(int32_t tOffsetMinutes);
      static int32_t ResolveUtcOffsetMinutes();
      static String ResolveTimeZoneLabel();
      static const char *ResolveBatteryStateKey();
      static String NormalizeStorageKey(const String &tRequestedStorage);
      static std::vector<const char *> GetStorageFilesByKey(const String &tStorageKey, const char *tDirectoryPath, const char *tExtension);
      static String NormalizeDashboardImageExtension(const String &tExtension);
      static bool IsStrictUploadFileName(const char *tFileName);
      static bool ResolveNextUploadFileName(const String &tStorageKey, const char *tDirectoryPath, char *tOutputFileName, size_t tOutputFileNameSize);
      static void NormalizeUploadFileNameToStorageExt(char *tFileName, size_t tFileNameSize);
      static const char *ResolveImageUploadErrorMessage(bool tIsThumb);
      static bool IsStorageAvailableByKey(const String &tStorageKey);
      static String GetDefaultStorageKey(const SStorageConfig &tStorageConfig);
      static bool IsStorageKeyAllowed(const String &tStorageKey, const SStorageConfig &tStorageConfig);
      static File OpenStorageFileByKey(const String &tStorageKey, const char *tPath, const char *tMode, bool tCreate = false);
      static bool StorageFileExistsByKey(const String &tStorageKey, const char *tPath);
      static bool DeleteStorageFileByKey(const String &tStorageKey, const char *tPath);
      static bool RenameStorageFileByKey(const String &tStorageKey, const char *tFromPath, const char *tToPath);
      static bool MakeStorageDirByKey(const String &tStorageKey, const char *tPath);
      static void InvalidateFileCacheByKey(const String &tStorageKey);
      static String GetStorageLeafFileName(const char *tPathOrFileName);
      static String ResolveNextStorageFileName(const String &tStorageKey, const char *tDirectoryPath, const char *tExtension, const char *tCurrentFileName);
      static bool ResolveStorageFileReadableSize(const String &tStorageKey, const char *tDirectoryPath, const char *tFileName, char *tOutputBuffer, size_t tOutputBufferSize);
      static bool CopyStorageFileByKey(const String &tSourceStorageKey, const char *tSourcePath, const String &tTargetStorageKey, const char *tTargetPath);
      static void AppendIndexDataJson(String &tJson, const SAppConfig &tConfig, const String &tStorageDefaultKey, const String &tImagesDirectory, const String &tImageExtension, uint64_t tSdUsedBytes, uint64_t tSdTotalBytes, uint64_t tLfsUsedBytes, uint64_t tLfsTotalBytes);
      static void AppendStatsDataJson(String &tJson, const SAppConfig &tConfig, uint64_t tSdUsedBytes, uint64_t tSdTotalBytes, uint64_t tLfsUsedBytes, uint64_t tLfsTotalBytes);
      static void AppendOtherPageDataJson(String &tJson, const String &tPageKey, const SAppConfig &tConfig, const String &tDashboardLanguage, const String &tStorageDefaultKey, unsigned long tTimestamp, int32_t tUtcOffsetMinutes, const String &tTimeZone);
      static String BuildErrorHtml(int tCode, bool tAuthorized);
      void RefreshDataCachesIfNeeded(bool tForce = false);
      void MarkGalleryCacheDirty();
      void RefreshGalleryCacheIfNeeded(bool tForce = false);
      void RefreshStatisticsCacheIfNeeded(bool tForce = false);
      bool ValidateToken(const char *tToken);
      bool AuthorizeRequest(AsyncWebServerRequest *tRequest);
      const char *CreateSession();
      void DestroySession(const char *tToken);
      void PurgeExpired();
      void RegisterRoutes();
      void OnWebSocketEvent(AsyncWebSocket *tWebSocket, AsyncWebSocketClient *tClient, AwsEventType tType, void *tEventArg, uint8_t *tData, size_t tLength);
      void OnWebSocketMessage(AsyncWebSocketClient *tClient, const char *tMessage, size_t tLength);
      void BroadcastOtaEvent(const char *tType, const char *tMessage, unsigned tProgress, const char *tState, const char *tModal = nullptr);
      void BroadcastStatus();
      void HandleLogin(AsyncWebServerRequest *tRequest);
      void HandleLogout(AsyncWebServerRequest *tRequest);
      void HandleStatus(AsyncWebServerRequest *tRequest);
      void HandlePageData(AsyncWebServerRequest *tRequest);
      void HandleConfigGet(AsyncWebServerRequest *tRequest);
      void HandleConfigSave(AsyncWebServerRequest *tRequest);
      void HandleDisplaySave(AsyncWebServerRequest *tRequest);
      void HandleNetworkSave(AsyncWebServerRequest *tRequest);
      void HandleMdnsSave(AsyncWebServerRequest *tRequest);
      void HandleNtpSave(AsyncWebServerRequest *tRequest, bool tSyncNow = false);
      void HandleDateTimeSave(AsyncWebServerRequest *tRequest);
      void HandleLanguageSave(AsyncWebServerRequest *tRequest);
      void HandleUserSave(AsyncWebServerRequest *tRequest);
      void HandleUserRestore(AsyncWebServerRequest *tRequest);
      void HandleWakeUpSave(AsyncWebServerRequest *tRequest);
      void ParseConfigSave(AsyncWebServerRequest *tRequest, SAppConfig &tConfig);
      void HandleImagesList(AsyncWebServerRequest *tRequest);
      void HandleImageDelete(AsyncWebServerRequest *tRequest, const String &tBody);
      void HandleImageImportUrl(AsyncWebServerRequest *tRequest);
      void HandleImageCopy(AsyncWebServerRequest *tRequest);
      void HandleImageUpload(AsyncWebServerRequest *tRequest, const String &tFilename, size_t tIndex, uint8_t *tData, size_t tLength, bool tFinal);
      void HandleImageDone(AsyncWebServerRequest *tRequest);
      void HandleOtaStatus(AsyncWebServerRequest *tRequest);
      void HandleOtaUpload(AsyncWebServerRequest *tRequest, const String &tFilename, size_t tIndex, uint8_t *tData, size_t tLength, bool tFinal);
      void HandleOtaDone(AsyncWebServerRequest *tRequest);
      void HandleReboot(AsyncWebServerRequest *tRequest);
      void HandleFactoryReset(AsyncWebServerRequest *tRequest);
      static size_t BuildStatusJson(char *tBuffer, size_t tSize);
      static size_t BuildConfigJson(char *tBuffer, size_t tSize, const SAppConfig &tConfig);
      static size_t BuildImagesJson(char *tBuffer, size_t tSize, const char *tDirectoryPath);
      void HandleStats(AsyncWebServerRequest *tRequest);
      void HandleImageRename(AsyncWebServerRequest *tRequest);
      void HandleImageSetCurrent(AsyncWebServerRequest *tRequest);
      void HandleImageFile(AsyncWebServerRequest *tRequest);
      void HandleImageThumb(AsyncWebServerRequest *tRequest);
      void HandleRtcSync(AsyncWebServerRequest *tRequest);
      void HandleRtcNow(AsyncWebServerRequest *tRequest);
      size_t BuildStatsJson(char *tBuffer, size_t tSize);
  };

}

#endif
