#ifndef DASHBOARD_PARTIALS_MODALS_USER_H
#define DASHBOARD_PARTIALS_MODALS_USER_H

#include <App/Global.h>

namespace App {
  namespace DashboardUserModals {
    const char Extra[] PROGMEM = R"PAGE(
<div id=user-restore-modal class=modal><div class=modal-dialog><div class=modal-header><span data-t=restore_settings></span><div class=modal-close data-modal-close role=button aria-label data-t-aria-label=close></div></div><div class=modal-body><p data-t=confirm_restore_settings></p></div><div class=modal-footer><a href=# class=button data-modal-close data-t=close></a><a href=# class="button button-primary" data-modal-close data-user-restore-confirm data-t=restore></a></div></div></div><div id=user-boot-target-modal class=modal><div class=modal-dialog><div class=modal-header><span data-t=boot_partition></span><div class=modal-close data-modal-close role=button aria-label data-t-aria-label=close></div></div><div class=modal-body><p data-t=confirm_boot_target_change></p></div><div class=modal-footer><a href=# class=button data-modal-close data-t=close></a><a href=# class="button button-primary" data-modal-close data-user-boot-target-confirm data-t=save></a></div></div></div><div id=user-format-sd-confirm-modal class=modal><div class=modal-dialog><div class=modal-header><span data-t=format_sd_card></span><div class=modal-close data-modal-close role=button aria-label data-t-aria-label=close></div></div><div class=modal-body><p data-t=confirm_format_sd_card></p></div><div class=modal-footer><a href=# class=button data-modal-close data-t=close></a><a href=# class="button button-danger" data-modal-close data-user-format-confirm data-user-format-target=sd_card data-t=format_sd_card></a></div></div></div><div id=user-format-littlefs-confirm-modal class=modal><div class=modal-dialog><div class=modal-header><span data-t=format_littlefs></span><div class=modal-close data-modal-close role=button aria-label data-t-aria-label=close></div></div><div class=modal-body><p data-t=confirm_format_littlefs></p></div><div class=modal-footer><a href=# class=button data-modal-close data-t=close></a><a href=# class="button button-danger" data-modal-close data-user-format-confirm data-user-format-target=littlefs data-t=format_littlefs></a></div></div></div><div id=user-format-progress-modal class=modal><div class=modal-dialog><div class=modal-header><span data-t=formatting_storage></span></div><div class=modal-body><div class=upload-progress data-user-format-progress-root aria-live=polite><small class=upload-progress-title data-user-format-progress-title data-t=formatting_storage></small><div class=upload-progress-inline><div class=upload-progress-track><div class=upload-progress-fill data-user-format-progress-fill style="width:0%"></div></div><span class=upload-progress-percent data-user-format-progress-percent>0%</span></div></div></div></div></div>
)PAGE";
  }
}

#endif
